language: go
sudo: required
go:
  - 1.7.3
os:
  - linux

script:
  - export GOOS=windows
  - export GOARCH=amd64
  - go get github.com/iovxw/downloader
  - go get github.com/lxn/walk
  - go get github.com/lxn/win
  - go get golang.org/x/net/html
  - go get golang.org/x/sys
